/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import com.revature.dao.*;
import com.revature.exceptions.InvalidAmountException;
import com.revature.exceptions.UsernameOrPasswordIncorrectException;
import com.revature.models.*;
import com.revature.services.*;
import io.javalin.Javalin;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Driver {

    private static final IUserDao uDao = new UserDaoMock();
    private static final UserService uServ = new UserService(uDao);
    private static final IAccountDao aDao = new AccountDaoMock();
    private static final AccountService aServ = new AccountService(aDao);
    private static final ITransactionDao tDao = new TransactionDaoMock();
    private static final TransactionService tServ = new TransactionService(tDao);


    public static void main(String[] args) {

        //Start Javalin Server
        Javalin server = Javalin.create(config -> {
            config.enableCorsForAllOrigins();
        });
        server.start(8000);


        //test of register user
        System.out.println("Testing User Registration...");
        uServ.registerUser("Artie", "Chungus", "BigChungus@email.com", "BigChungus", "mond0C00l", 1);
        System.out.println("New user " + uDao.getUserByUsername("BigChungus").getUsername() + " has been registered \n");

        //test of User Dao
        System.out.println("Testing User Dao To Retrieve User Info...");
        System.out.println(uDao.getUserByUsername("BigChungus") + "\n");


        //test of successful login
        System.out.println("Testing Successful User Login...");
        try {
            uServ.loginUser("BigChungus", "mond0C00l");
            User u = uDao.getUserByUsername("BigChungus");
            System.out.println(u.getUsername() + " login status: " + u.isLoggedIn() + "\n");
        } catch(UsernameOrPasswordIncorrectException e) {
            e.printStackTrace();
        }

        //test of unsuccessful login
        System.out.println("Testing Unsuccessful User Login...");
        try {
            uServ.loginUser("BigChungus", "wrong");
            System.out.println(uDao.getUserByUsername("BigChungus").getUsername() + " has successfully logged in \n");
        } catch(UsernameOrPasswordIncorrectException e) {
            e.printStackTrace();
        }

        //test of logout
        System.out.println("Testing User Logout...");
        try{
            uServ.logoutUser("BigChungus");
            User u = uDao.getUserByUsername("BigChungus");
            System.out.println(u.getUsername() + " login status: " + u.isLoggedIn() + "\n");
        } catch (UsernameOrPasswordIncorrectException e){
            e.printStackTrace();
        }

        //Test of account creation
        System.out.println("Testing account creation...");
        User u = uDao.getUserByUsername("BigChungus");
        aServ.createAccount("Checking",(Integer) 1, u);
        aServ.createAccount("Savings", (Integer) 2, u);

        //Test of Account database
        System.out.println("testing Account Dao...");
        System.out.println(aDao.getAccountsByUsername("BigChungus") + "\n");

        //test if account added to user object
        System.out.println("Test to see if account added to user object...");
        System.out.println(u.toString());

        //Deposit funds into BigChungus Checking account
        System.out.println("Depositing funds into BigChungus checking account...");
        java.util.Date timeStamp = new java.util.Date();
        Account chungusChecking = aDao.getAccountById((Integer) 1, "BigChungus");
        try {
            tServ.deposit("Deposit", u, chungusChecking, 1000, timeStamp);
            System.out.println("Checking account Status: " + chungusChecking.toString());
        }catch(InvalidAmountException e){
            e.printStackTrace();
        }
    }
}
